### ISSUE TITLE
How to run **dates-from-sample-ids.nb**

### ISSUE THREAD

**Issue by ghost** [blab/ebola-dates#1]
How to  run **dates-from-sample-ids.nb** to get the results, thanks.
How to use these imputations as informed priors in a BEAST analysis to further estimate sampling dates?
thanks.

**Comment by trvrb** [comment]
`dates-from_sample-ids.nb` is a Mathematica notebook. This repo was never fully developed. And imputations were not used in BEAST. I've ammended readme here: https://github.com/blab/ebola-dates/commit/c605c92840339d2c84fff93b2eb0b9c5e98ee804.
